name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: ./mvnw install -DskipTests

      - name: Run tests
        run: ./mvnw test

      - name: Package application
        run: ./mvnw package
        env:
          CI: true

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Environment
        run: echo "Deploy logic here" # Substitua com o comando para implantar a aplicação
